apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-service-deployment
  labels:
    team: a14app
spec:
  selector:
    matchLabels:
      app: citizen-service
  template:
    metadata:
      labels:
        app: citizen-service
    spec:
      containers:
        - name: citizen-container
          image: mhkars/citizen-service:v001
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.2"
          ports:
            - containerPort: 7777

