apiVersion: v1
kind: Service
metadata:
  name: citizen-cluster
spec:
  type: LoadBalancer
  selector:
    app: citizen-service
  ports:
    - port: 7777
      targetPort: 7777
      name: citizen-service-port
